CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210608104929_InitMigration') THEN
    CREATE TABLE tv_shows (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(60) NOT NULL,
        genre integer NOT NULL,
        rating numeric NOT NULL,
        imdb_url text NOT NULL,
        image_url text NOT NULL,
        CONSTRAINT pk_tv_shows PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210608104929_InitMigration') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20210608104929_InitMigration', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20210708035502_SciFiCategory') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20210708035502_SciFiCategory', '5.0.7');
    END IF;
END $$;
COMMIT;

